name: "generate weekly"

on:
  workflow_dispatch:
    inputs:
      uri:
        description: 'github uri'
        required: true
      is_download:
        description: '是否下载图片'
        required: true
        default: false
        type: choice
        options:
          - false
          - true
      description_var:
        description: '描述'
        required: false
        type: string

env:
  TZ: Asia/Shanghai

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v2
        with:
          go-version: 1.19
      - name: "generate weekly"
        timeout-minutes: 3
        env:
          APP_ENV: "prod"
          GITHUB_OWNER: "xiaoxuan6"
          GITHUB_EMAIL: "1527736751@qq.com"
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          go mod tidy
          go run cmd/generate_weekly.go --uri="${{ inputs.uri }}" --is_download="${{ inputs.is_download }}" --description_var="${{ inputs.description_var }}"
