name: Update README.md

on:
  repository_dispatch:
    types:
      - push

env:
  TZ: Asia/Shanghai

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: "run"
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements.txt
          python main.py --url="${{ github.event.client_payload.url }}" --description="${{ github.event.client_payload.description }}" --demo_url="${{ github.event.client_payload.demo_url }}"
      - name: "Commit files"
        run: |
          git config --local user.email "1527736751@qq.com"
          git config --local user.name "xiaoxuan6"
          git add -A
          git commit -m "fix: Update README.md" || exit 0
      - name: "Push changes"
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true

  save:
    needs: upload
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - name: "run"
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: 3306
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
        run: |
          go mod tidy
          go run cmd/main.go --url="${{ github.event.client_payload.url }}" --name="${{ github.event.client_payload.description }}"
